### ISSUE TITLE
NativeInheritance attributes with missing/incorrect base types

### ISSUE THREAD

**Issue by rickbrew** [terrafx/terrafx.interop.windows#214]
Found these while experimenting with a generator for the `PUnknown` wrappers I was talking about on Discord.

The assumption is that `[NativeInheritance("FOO")]` means that a `TerraFx.Interop.FOO` entity exists, retrievable via `assembly.GetType("TerraFX.Interop.FOO")`. For these, that's not true:

```
Missing base type IDispatchEx for IIE70DispatchEx
Missing base type IDispatchEx for IIE80DispatchEx
Missing base type tagBIND_OPTS for BIND_OPTS2
Missing base type tagBIND_OPTS2 for BIND_OPTS3
Missing base type tagMONITORINFO for MONITORINFOEXA
Missing base type tagMONITORINFO for MONITORINFOEXW
Missing base type tagMOUSEHOOKSTRUCT for MOUSEHOOKSTRUCTEX
```

This doesn't block me, I can just skip them for now. Could be a useful unit test though.

**Comment by tannergooding** [comment]
These exist for everything now, just that `NativeInheritance` exposes the native name, such as `tagBIND_OPTS` where as the exposed type might be `BIND_OPTS` due to the expected typedef.

You can detect this via the `Base` field or by looking at the `.Interface` nested type and the interface it inherits from.
