### ISSUE TITLE
SHELLEXECUTEINFOW size is wrong on x64/arm64

### ISSUE THREAD

**Issue by rickbrew** [terrafx/terrafx.interop.windows#219]
The size of this struct is supposed to be 112, but it's defined with `Pack=1` and ends up with a size of 104 on x64 (and probably arm64). This is preventing `ShellExecuteExW()` from working, it just returns `ERROR_ACCESS_DENIED`.

**Comment by rickbrew** [comment]
I'm going to guess that any header file that conditionally uses `pshpack1.h` may also be affected

This is what `shellapi.h` does,

```
#if !defined(_Wi gIN64)
#include <pshpack1.h>
#endif
```

**Comment by tannergooding** [comment]
This is resolved, as best as I think can be handled, via https://github.com/terrafx/terrafx.interop.windows/pull/228.

The packing differs between 32-bit and 64-bit and so the types are split into `T32` and `T64` variants now. There exists a general `T` struct still, but it is a union of the `T32` and `T64` types and handles correctly exposing the fields via `ref` returning properties.

The major "gotcha" here is that you must use `T.SizeOf` rather than `sizeof(T)` for these `um/SetupAPI` and `um/ShellAPI` types.
