### ISSUE TITLE
Consider moving DirectX CLSID's into DirectX namespace

### ISSUE THREAD

**Issue by rickbrew** [terrafx/terrafx.interop.windows#276]
e.g.

`CLSID.CLSID_D2D1AlphaMask`

**Comment by tannergooding** [comment]
enerally yes, all DX stuff in DX
but there is always going to be some wonkiness between things
simply due to how the Windows SDK works
e.g. half the errors are in winerror, even for DX

I think the right thing here is to instead expose:
```csharp
[Guid(...)]
struct D2D1AlphaMask { }
```

This is the general pattern followed by some, but not all headers. That is, some headers define CLSID/LIBID/IID on opaque types and expose them that way. Others only define them manually.

For consistency and making `__uuidof<T>` possible to universally use in .NET 7+, I think normalizing to having a type is a generally good approach
