### ISSUE TITLE
Trying to use latest ClangSharpPInvokeGenerator with this repo

### ISSUE THREAD

**Issue by xoofx** [terrafx/terrafx.interop.windows#367]
Hey, I'm trying to see If I can add some new Windows APIs, so I installed the latest ClangSharpPInvokeGenerator 17.0.0 and tried to run it, but then after while trying to compile the solution, I'm getting a few compilation errors (e.g uuidof not working because `INativeGuid` are missing and a few others, not many, like 18 errors).

Is there anything special to do or to update with this version?

**Comment by tannergooding** [comment]
There's currently 5 generated files with issues:
* `sources/Interop/Windows/DirectX/um/d2d1_1/ID2D1Effect.cs`
  * needs pragma warning disable CA1508
* `sources/Interop/Windows/WinRT/winrt/windows.ui.composition.interop/ICompositorInterop2.cs`
  * uses IInspectable, not ICompositionTexture (still need to expose the latter)
* `sources/Interop/Windows/Windows/shared/ws2ipdef/Windows.cs`
  * ClangSharp fails to emit the `&` to take the address
* `sources/Interop/Windows/Windows/um/Unknwnbase/IUnknown.cs`
  * ClangSharp has no way to emit INativeGuid for the base type of the interface today
* `sources/Interop/Windows/Windows/um/mfobjects/MF_Plugin_Type.cs`
  * ClangSharp casts the enum value to `uint` unnecessarily because the C code casts to `DWORD`, even though the enum type is actually `int`

Everything else should be getting correctly generated (using a locally built copy of ClangSharp -- working on getting some changes done and published in a new v17.0.1 tool).

**Comment by xoofx** [comment]
Thanks, didn't have time to check but I will try again.
